services:
  db:
    image: postgres
    container_name: postgres-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
      POSTGRES_DB: myappdb
    ports:
      - "5432:5432"
    volumes:
      - todoapp_pgdata:/var/lib/postgresql

volumes:
  todoapp_pgdata:
